language: node_js

before_script:
  - npm run install

after_success:
  - npm run install

jobs:
  include:
     - name: Sentry Release
          env: SENTRY_ORG=coronasafe-network SENTRY_PROJECT=care-fe SENTRY_ENVIRONMENT=production
          script: |
            curl -sL https://sentry.io/get-cli/ | bash
            export SENTRY_RELEASE=$(sentry-cli releases propose-version)
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
            sentry-cli releases set-commits $SENTRY_RELEASE --auto
            sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps path-to-sourcemaps-if-applicable
            sentry-cli releases finalize $SENTRY_RELEASE
            sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
